name: 'Deploy Template'

env:
  NUXT_SHOPIFY_NAME: ${{ secrets.NUXT_SHOPIFY_NAME }}

  NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN }}

  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  NUXT_SHOPIFY_DEV_MODULE_ALIAS: true

on:
  push:
    branches:
      - main

concurrency:
  group: template
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Typecheck
        run: bun run prepare && bun run prepare:template && bun run typecheck:template

  deploy:
    runs-on: ubuntu-latest
    needs: [ typecheck ]
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install Vercel CLI
        run: bun install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Build Environment Variables
        run: vercel env pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Template
        run: vercel build --prod

      - name: Deploy Project to Vercel
        run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
