name: 'Release Module'

env:
  NUXT_SHOPIFY_NAME: ${{ secrets.NUXT_SHOPIFY_NAME }}

  NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN }}

  NUXT_SHOPIFY_CLIENTS_ADMIN_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_ADMIN_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_ADMIN_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_CLIENTS_ADMIN_ACCESS_TOKEN }}

  NUXT_SHOPIFY_DEV_MODULE_ALIAS: true

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Lint
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Typecheck Module
        run: bun run prepare && bun run typecheck

      - name: Typecheck All Playgrounds
        run: bun run typecheck:playgrounds

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Run tests
        run: bun run prepare && bun run prepare:playgrounds && bun run test:coverage

  release:
    runs-on: ubuntu-latest
    env:
      NUXT_SHOPIFY_DEV_MODULE_ALIAS: false
    needs: [ lint, typecheck, test ]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: 24.11.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Build
        run: bun run prepare && bun run build

      - name: Release module
        run: npm publish
