name: 'Tests'

env:
  NUXT_SHOPIFY_NAME: ${{ secrets.NUXT_SHOPIFY_NAME }}

  NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_CLIENTS_STOREFRONT_PUBLIC_ACCESS_TOKEN }}

  NUXT_SHOPIFY_CLIENTS_ADMIN_API_VERSION: ${{ secrets.NUXT_SHOPIFY_CLIENTS_ADMIN_API_VERSION }}
  NUXT_SHOPIFY_CLIENTS_ADMIN_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_CLIENTS_ADMIN_ACCESS_TOKEN }}

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Lint
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Typecheck Module
        run: bun run prepare && bun run typecheck

      - name: Typecheck All Playgrounds
        run: bun run typecheck:playgrounds

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Run tests
        run: bun run prepare && bun run prepare:playgrounds && bun run test:coverage

  build:
    runs-on: ubuntu-latest
    needs: [ lint, typecheck, test ]

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Build
        run: bun run prepare && bun run build
